name: Github Page Deploy

on:
  push:
    branches:
      - "gh-app"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      apiKey: ${{ secrets.APIKEY }}
      authDomain: ${{ secrets.AUTHDOMAIN }}
      projectId: ${{ secrets.PROJECTID }}
      storageBucket: ${{ secrets.STORAGEBUCKET }}
      messagingSenderId: ${{ secrets.MESSAGINGSENDERID }}
      appId: ${{ secrets.APPID }}
      measurementId: ${{ secrets.MEASUREMENTID }}

    strategy:
      matrix:
        node-version: [ 15.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and Build
        run: npm install && npm run build
        env:
          CI: true
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build