name: Github Page Deploy

on:
  push:
    branches:
      - "gh-app"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create env file
        run: |
          touch .env.local
          echo REACT_APP_API_KEY = ${{ secrets.APIKEY }}
          echo REACT_APP_AUTH_DOMAIN = ${{ secrets.AUTHDOMAIN }}
          echo REACT_APP_PROJECT_ID = ${{ secrets.PROJECTID }}
          echo REACT_APP_STORAGE_BUCKET = ${{ secrets.STORAGEBUCKET }}
          echo REACT_APP_MESSAGING_SENDER_ID = ${{ secrets.MESSAGINGSENDERID }}
          echo REACT_APP_MESSAGING_APP_ID = ${{ secrets.APPID }}
          echo REACT_APP_MEASUREMENT_ID = ${{ secrets.MEASUREMENTID }}
      - name: Install and Build
        run: npm install && npm run build
        env:
          CI: false
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build