name: "publish"

on:
  push:
    branches: [ component/popup ]

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: version upgrade
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          npm version patch -m "v%s"
          VERSION=$(node -p "require('./package.json').version")
          git tag ${VERSION}
          git push "https://$GITHUB_ACTOR:${{ secrets.GIT_AUTH_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags
          git push "https://$GITHUB_ACTOR:${{ secrets.GIT_AUTH_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --tags
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
