name: "publish"

on:
  push:
    branches: [ component/popup ]

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Version app
        run: |
          npm version patch
          date > generated.txt
          git config --global user.name farunurisonmez
          git config --global user.email info@farunurisonmez.com
          git add .
          git commit -m "generated"
          git push
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
