name: "publish"

on:
  push:
    branches: [ component/popup ]

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3

      - name: Setup Node
        # Setup node environment
        uses: actions/setup-node@v3
      - name: version upgrade
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          npm version patch -m "v%s"
          VERSION=$(node -p "require('./package.json').version")
          git tag ${VERSION}
          git push "https://$GITHUB_ACTOR:${{ secrets.GIT_AUTH_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags
          git push "https://$GITHUB_ACTOR:${{ secrets.GIT_AUTH_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --tags
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
